# Fyodor's default config.

# Set the translations you get on your clippings file.
[parser]
highlight = "Tu subrayado"
note = "Tu nota"
bookmark = "Tu marcador"
clip = "Clip This Article"
loc = "Posición"
page = "en la página"
time = "Añadido el"

[output]
filename = "%{author_fill} - %{title}.md"
